# Generated by Django 5.2.6 on 2025-09-21 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('industry_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('gwp', models.FloatField(help_text='Global Warming Potential')),
            ],
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mines', to='emissions.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('emission_value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('co2_equivalent', models.FloatField()),
                ('method_notes', models.TextField(blank=True, null=True)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='emissions.mine')),
                ('pollutant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.pollutant')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('submitted_to', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='emissions.company')),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='emissions.mine')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=100)),
                ('installation_date', models.DateField()),
                ('last_calibrated', models.DateField(blank=True, null=True)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='emissions.mine')),
                ('pollutant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.pollutant')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('quality_flag', models.CharField(blank=True, max_length=20, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='emissions.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
